name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        echo "Building the project"
        ls

    - name: Test
      run: |
        echo "Running tests"
        test -f index.html
